version: 0.0
os: linux

files:
  - source: /
    destination: /var/www/html

hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: scripts/start_nginx.sh
      timeout: 300
      runas: root

  ValidateService:
    - location: scripts/deploy_notify.sh
      arguments: ["auto", "CodeDeploy"]   # Automatically detects success/failure/rollback
      timeout: 60
      runas: root
