version: 0.0
os: linux

files:
  - source: /
    destination: /var/www/html

hooks:
  BeforeInstall:
    - location: scripts/hook_wrapper.sh
      arguments: ["scripts/before_install.sh", "BeforeInstall"]
      timeout: 300
      runas: root

  AfterInstall:
    - location: scripts/hook_wrapper.sh
      arguments: ["scripts/after_install.sh", "AfterInstall"]
      timeout: 300
      runas: root

  ApplicationStart:
    - location: scripts/hook_wrapper.sh
      arguments: ["scripts/start_nginx.sh", "ApplicationStart"]
      timeout: 300
      runas: root

  ValidateService:
    - location: scripts/hook_wrapper.sh
      arguments: ["success_marker", "ValidateService"]
      timeout: 300
      runas: root
